image: gitpod/workspace-full-vnc
# Update 7th September to reflect code base changes
ports:
- name: JBrowseWeb
  description: The JBrowse Webserver port
  port: 3000
  onOpen: open-browser
  visibility: public

- name: HiGlass
  description: The HiGlass port
  port: 8989
  onOpen: open-browser
  visibility: public

tasks:
  - name: Install Nextflow
  # https://www.nextflow.io/docs/latest/getstarted.html
    init: |
      cd /workspace/treeval-curation/
      
      wget -qO- https://get.nextflow.io | bash

      chmod +x nextflow

      sudo mv nextflow /usr/local/bin

  - name: Install JBrowse2
  # https://jbrowse.org/jb2/download/#jbrowse-cli-tools
    command: |
      cd /workspace/treeval-curation/
      
      npm install -g @jbrowse/cli serve

      jbrowse create jbrowse2

      cd jbrowse2/

      npx serve . -l 3000

  - name: Install TreeVal Pipeline
  # https://github.com/sanger-tol/treeval
    init: |
      cd /workspace/treeval-curation/
        
      git clone -b 1.1.1 https://github.com/sanger-tol/treeval.git

  - name: Install FasMan
    # https://github.com/Rust-Wellcome/FasMan
    init: |
      cd /workspace/treeval-curation/
      
      git clone https://github.com/Rust-Wellcome/FasMan.git -b dp24_split_scaff

      cd /workspace/treeval-curation/FasMan/
      
      cargo run -- -h

  - name: Install Curation Pretext
  # https://github.com/sanger-tol/curationpretext
    init: |
      cd /workspace/treeval-curation/

      git clone -b 1.0.0 https://github.com/sanger-tol/curationpretext.git

  - name: Install HiGlass
  # https://docs.higlass.io/tutorial.html
    init: |
      cd /workspace/treeval-curation/
      
      pip install higlass-manage

      higlass-manage start

  - name: Download busco for nematode
    init: |
      cd /workspace/treeval-curation/

      curl https://dp24.cog.sanger.ac.uk/Busco.tar.gz | tar xzf -

  - name: Download Nematode Test data and make synteny
    init: |
      cd /workspace/treeval-curation/

      curl https://dp24.cog.sanger.ac.uk/Nematode.tar.gz | tar xzf -

      mkdir -p /workspace/treeval-curation/synteny/nematode/

      cp /workspace/treeval-curation/Oscheius_DF5033/genomic_data/Oscheius_DF5033.fa /workspace/treeval-curation/synteny/nematode/SuperNematode.fa

  - name: Download Lepidoptera data
    init: |
      cd /workspace/treeval-curation/

      curl https://dp24.cog.sanger.ac.uk/ilTorViri5.tar.gz | tar xzf -

  - name: Download Genomic Alignment data
    init: |
      cd /workspace/treeval-curation/

      curl https://dp24.cog.sanger.ac.uk/AlignmentData.tar.gz | tar xzf -  

  - name: Open Tutorial Page
    init: |
      gp preview https://thebgacademy.org/BGA24/Session-Documents/TreeVal/TreeVal-Tutorial

vscode:
  extensions:                               # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore                # Language support for .gitignore files
    - esbenp.prettier-vscode                # Markdown/CommonMark linting and style checking for Visual Studio Code
    - EditorConfig.EditorConfig             # override user/workspace settings with settings found in .editorconfig files
    - mechatroner.rainbow-csv               # Highlight columns in csv files in different colors
    - nextflow.nextflow                     # Nextflow syntax highlighting
    - oderwat.indent-rainbow                # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
